version: '3'  # docker-compose 파일 버전
services:
  app:  # 서비스 이름
    image: pyjhoop/app:latest  # 사용할 이미지
    container_name: app-green
    environment:
      - LANG=ko_KR.UTF-8
    ports:
      - "8082:8080"  # 호스트의 8080 포트를 컨테이너의 80 포트에 매핑